[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.155.2"

[build.processing]
  skip_processing = ["static/admin/*"]

# [[redirects]]              ‚Üê COMMENTATO: NO LOOP!
#   from = "/admin"
#   to = "/admin/"
#   status = 301
#   force = true
